spring.application.name=appreceitas

# DataSource
spring.datasource.url=jdbc:h2:file:./data/exemplo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=password

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Permite acesso fora ambiente locahost H2
spring.h2.console.settings.web-allow-others=true

# Reescrita de cabeçalho HTTP
server.forward-headers-strategy=framework
spring.application.name=devtech-store

spring.thymeleaf.cache=false

